#! /bin/bash

# this requires the "inotify-tools", install with:
#   sudo zypper in inotify-tools

# cd to file directory first
dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)
cd "$dir/.."

while true
do
  # generate the status page
  ./y2status "$@" -v -o devel/index.html
  # wait for a file modificatin
  inotifywait --recursive --event modify --timeout 300 y2status lib views config
  # make sure all changes are written
  sleep 1
done