#!/usr/bin/env ruby

# install missing gems
if !File.exist?(".vendor")
  puts "Installing the needed Rubygems to .vendor/bundle ..."
  system "bundle install --path .vendor/bundle"
end

require "rubygems"
require "bundler/setup"

require "octokit"
require "parallel"
require "ruby-progressbar"
require "yaml"
require "singleton"
require "optparse"
require "shellwords"


module Y2sync
  # FIXME: more branches
  IGNORED_REPOS = {
    # FIXME
    "SLE-12-GA" => [],
    "SLE-12-SP1" => [],
    "SLE-12-SP2" => [],
    "SLE-12-SP3" => [],
    "SLE-12-SP4" => [],
    "SLE-15-GA" => [],
    "SLE-15-SP1" => [],
    "SLE-15-SP2" => [],
    "SLE-15-SP3" => [],
    "SLE-15-SP4" => [],
    "master" => [
      "skelcd-control-SLES-for-VMware",
      "rubygem-scc_api",
      "yast-autofs",
      "yast-backup",
      "yast-bluetooth",
      "yast-boot-server",
      "yast-cd-creator",
      "yast-certify",
      "yast-cim",
      "yast-databackup",
      "yast-dbus-client",
      "yast-debugger",
      "yast-dialup",
      "yast-dirinstall",
      "yast-fax-server",
      "yast-fingerprint-reader",
      "yast-heartbeat",
      "yast-hpc",
      "yast-ipsec",
      "yast-irda",
      "yast-iscsi-server",
      "yast-kerberos-client",
      "yast-kerberos-server",
      "yast-liby2util",
      "yast-live-installer",
      "yast-ldap-client",
      "yast-ldap-server",
      "yast-lxc",
      "yast-meta",
      "yast-mouse",
      "yast-mail-server",
      "yast-mysql-server",
      "yast-ntsutils",
      "yast-oem-installation",
      "yast-online-update-test",
      "yast-openschool",
      "yast-openteam",
      "yast-openvas-security-scanner",
      "yast-openwsman-yast",
      "yast-packagemanager",
      "yast-packagemanager-test",
      "yast-phone-services",
      "yast-power-management",
      "yast-profile-manager",
      "yast-repair",
      "yast-restore",
      "yast-runlevel",
      "yast-squidguard",
      "yast-sshd",
      "yast-sudo",
      "yast-support",
      "yast-system-profile",
      "yast-system-update",
      "yast-slepos-image-builder",
      "yast-slepos-system-manager",
      "yast-slide-show",
      "yast-tv",
      "yast-ui-qt-tests",
      "yast-update-alternatives",
      "yast-uml",
      "yast-wagon",
      "yast-you-server",
      "yast-yxmlconv",
      "yast-y2pmsh",
      "yast-y2r-tools",
      "ycp-killer",
      "y2r",
      "travis_old"
    ]
  }

  class Options
    include Singleton

    attr_reader :verbose, :branch, :command, :require
    attr_writer :command

    def initialize
      OptionParser.new do |opts|
        opts.banner = "Usage: #{$PROGRAM_NAME} [options] [command]"
      
        opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
          self.verbose = v
        end

        opts.on("-r", "--require", "Require a file") do |r|
          self.require = r
        end

        opts.on("-b", "--branch", "Branch to checkout (default \"master\")") do |b|
          self.branch = b
        end
      end.parse!

      self.command = ARGV.shift
      self.branch = "master" unless branch
    end

  private

    attr_writer :verbose, :branch, :require
  end

  class Config
    FILE_NAME = ".y2sync.yml".freeze

    attr_reader :branch, :empty_repos, :file

    def initialize(file: nil, branch: "master", empty_repos: [])
      @file = file
      @branch = branch
      @empty_repos = empty_repos
    end

    def self.read(file = FILE_NAME)
      dir = Dir.pwd
      path = File.join(dir, file)

      while !File.exist?(path) && dir != "/"
        dir = Pathname.new(dir).parent.to_s
        path = File.join(dir, file)
      end

      if File.exist?(path)
        cfg = YAML.load_file(path)
        config = Config.new(file: path, branch: cfg["branch"], empty_repos: cfg["empty_repos"])
        return config
      end

      Config.new
    end

    def write
      cfg = {
        "branch"      => branch,
        "empty_repos" => empty_repos
      }
      puts "Writing #{file || FILE_NAME}"
      File.write(file || FILE_NAME, cfg.to_yaml)
    end
  end

  class SyncResult
    attr_reader :success
    attr_reader :empty_repo
    attr_reader :error_msg

    def initialize(success:, empty_repo:, error_msg:)
      @success = success
      @empty_repo = empty_repo
      @error_msg = error_msg
    end
  end

  class Repo
    def self.all
      client = Octokit::Client.new
      client.auto_paginate = true

      # TODO add option for other organizations
      client.list_repositories("yast").map(&:name).sort
    end

    def self.branch(branch)
      all.reject{ |r| IGNORED_REPOS[branch].include?(r.name)}
    end

    def self.sync_all(repos)
      Parallel.map(repos, progress: "Progress") { |r| r.sync }
    end

    # octokit info
    attr_reader :repo

    def initialize(info)
      @repo = info
    end

    def dir
      # remove the "yast-" prefix, make searching in the directory easier
      repo.name(/^yast-/, "")
    end

    def clone_repo
      cmd = "git clone -b #{Shellwords.escape(TARGET_BRANCH)} " \
        "#{Shellwords.escape(repo.git_url)} #{Shellwords.escape(dir)}"

      `#{cmd}`

      # FIXME: collect errors?
      SyncResult.new(success: $?.success?, empty_repo: live?)
    end

    def update_repo
      Dir.cwd(dir) do
        # stash - make sure any unsubmitted work is not lost by accident
        # reset - ensure consistent state
        # prune - remove the branches which were deleted on the server
        # checkout - ensure the requested branch is set
        # pull - update from origin with rebase
        # TODO: optionally gc
        cmd = "git stash save && git reset --hard && git fetch --prune && " \
          "git checkout -q #{Shellwords.escape(TARGET_BRANCH)} && git pull --rebase"
        `#{cmd}`

        return SyncResult.new(success: $?.success?, empty_repo: live?)
      end
    end

    def sync
      # clone or update the existing checkout
      if File.exist?(dir)
        update_repo
      else
        clone_repo
      end
    end

  private

    def files
      # remove the self and parent directory entries
      Dir.entries(dir) - [".", ".."]
    end

    # the dead repositories only contain README.md file
    def live?
      files.size > 1
    end
  end
end

def main
  options = Y2sync::Options.instance
  puts "options: #{options.inspect}"

  config = Y2sync::Config.read
  puts "config: #{config.inspect}"

  if options.command.nil?
    options.command = config.file.nil? ? "clone" : "refresh"
  end

  case  options.command
  when "clone"
    puts "Cloning all repositories..."
    puts Y2sync::Repo.all.inspect
    #config.write
  when "refresh"
    puts "Refreshing the current repositories..."
  when "update"
    puts "Updating the current checkout..."
  end
  puts "options: #{options.inspect}"

end

main

