# This configuration files defines all projects scanned by
# the y2status tool.

jenkins:
  # Jenkins servers
  - label: External Jenkins - YaST
    url: https://ci.opensuse.org/view/Yast
    ignore:
      - clang
      - werror
  - label: External Jenkins - libyui
    url: https://ci.opensuse.org/view/libyui
    ignore:
      - gtk

  - label: Internal Jenkins - YaST
    url: https://ci.suse.de/view/YaST
    internal: true
    ignore:
      - yast-autoyast-profiles-test
  - label: Internal Jenkins - libyui
    url: https://ci.suse.de/view/libyui
    internal: true
  - label: Internal Jenkins - InstallTools
    url: https://ci.suse.de/view/InstallTools
    internal: true

obs:
  # OBS projects
  - project: YaST:Head
  - project: YaST:SLE-15:GA
  - project: YaST:SLE-12:SP4
  - project: YaST:SLE-12:SP3
  - project: devel:libraries:libyui
  - project: system:install:head
    # only the packages maintained by the YaST team
    packages:
      - checkmedia
      - hwinfo
      - installation-images
      - libx86emu
      - linuxrc
      - linuxrc-devtools
      - mkdud
      - mksusecd

  # IBS projects
  - project: Devel:YaST:Head
    api: https://api.suse.de
    internal: true
    ignore:
      - SUSE_Factory_Head

  - project: Devel:YaST:CASP:4.0
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:SLE-15
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:SLE-12-SP4
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:SLE-12-SP3
    api: https://api.suse.de
    internal: true
